### ISSUE TITLE
Requesting your help / Flutter Game Engine 

### ISSUE THREAD

**Issue by nmfisher** [nmfisher/flutter_filament#24]
I mentioned in another issue that I've actually extended this repository with some basic game engine components, which allowed me to submit a 3D game for the Flutter game competition. 

This was received pretty well, and is currently is in the top 20 submissions. There's a second round of judging, and it would really help if people could vote for my submission. If the game gets into the top 10, it would really help get more exposure for this repository, and might help get some more resources to add further functionality.

So if you like the game, please vote!

https://devpost.com/software/escape-from-heat-island 

![Screenshot 2024-04-24 at 10 21 50 AM](https://github.com/nmfisher/flutter_filament/assets/7238578/0e24b827-8da0-451a-8e0e-393d8f52ae0c)

**Comment by Hannnes1** [comment]
Voted!
You could try posting in the Discord and subreddit as well. Might give you a few more votes.
I know I'm not the only one that has been waiting to have 3D in Flutter.

**Comment by nmfisher** [comment]
Thank you! Good idea - I'm actually planning to write a blog post on the game engine-y bits to share to the Discord/subreddit at the same time so it's not just blatant self-promotion :smile:

**Comment by Hannnes1** [comment]
Nice. That would be interesting to read.

**Comment by nmfisher** [comment]
Thanks to everyone who helped! Voting has finished so I'll close this issue.
